# fly.toml app configuration file
# This file is generated when you deploy from GitHub

app = "your-app-name"  # Fly.io will auto-generate this
primary_region = "ord"  # Change to your preferred region

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "10s"
    path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 2048  # 2GB RAM for your AI models